module.exports = {
  // mac os events
  playToggle: 'desktopPlayToggle',
  historyFwd: 'desktopHistoryForward',
  historyBack: 'desktopHistoryBack',
  volumeUp: 'desktopVolumeUp',
  volumeDown: 'desktopVolumeDown',
  // custom events
  fbAuthenticate: 'fb-authenticate',
  fbAuthenticated: 'fb-authenticated',
  navigateToAccount: 'navigate-account',
  navigateToOptOutPage: 'navigate-opt-out',
  openGdprSettings: 'open-gdpr-settings',
  enableMenuPlayPause: 'enableMenuPlayPause',
  search: 'desktopSearch',
  openShareDialog: 'openShareDialog',
  logClientError: 'logClientError',
  setUpLocalizations: 'setUpLocalizations',
  setUpGeminiEventSender: 'setUpGeminiEventSender',
  setMainWebContents: 'setMainWebContents',
  activateDesktopUpdateBanner: 'activateDesktopUpdateBanner',
  quitDesktopAndInstallUpdate: 'quitDesktopAndInstallUpdate',
  showOptOutPageMenuItem: 'showOptOutPageMenuItem',
  hideOptOutPageMenuItem: 'hideOptOutPageMenuItem',
  showGdprSettingsMenuItem: 'showGdprSettingsMenuItem',
  hideGdprSettingsMenuItem: 'hideGdprSettingsMenuItem',
  reloadPage: 'reloadPage',
  handleGoogleAuth: 'handleGoogleAuth',
  openGoogleAuth: 'openGoogleAuth',
};
