module.exports = {
  rtid: 'rtid',
  partnerId: 'partnerId',
  windowBounds: 'windowBounds',
  nuteinTweaksEnabled: 'nuteinTweaksEnabled',
  nuteinAdsEnabled: 'nuteinAdsEnabled',
  nuteinDisableTelemetryCrashReports: 'nuteinDisableTelemetryCrashReports',
  nuteinDisableUpdates: 'nuteinDisableUpdates',
  nuteinHidePremiumMenu: 'nuteinHidePremiumMenu',
  nuteinHideAudiobooksMenu: 'nuteinHideAudiobooksMenu',
  nuteinHideRadioMenu: 'nuteinHideRadioMenu',
  nuteinHideRecentsMenu: 'nuteinHideRecentsMenu',
  nuteinHideMusicMenu: 'nuteinHideMusicMenu',
  nuteinHideSportsMenu: 'nuteinHideSportsMenu',
  nuteinHideNewsMenu: 'nuteinHideNewsMenu',
  nuteinHidePodcastsMenu: 'nuteinHidePodcastsMenu',
  nuteinHideRegionsMenu: 'nuteinHideRegionsMenu',
  nuteinHideLanguagesMenu: 'nuteinHideLanguagesMenu',
};
